version: '3.7'

services:
  web:
    image: travismillerdev/snap-screener-web-base:latest
    volumes:
      - ./web/api:/var/www/api
      - ./web/build:/var/www/html
    ports:
      - 5000:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
