version: '3.7'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.local
    volumes:
      - ./web/api:/var/www/api
      - ./web/build:/var/www/html
    ports:
      - 3000:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
